version: '2'

services:

  nginx:
    image: "nginx:1.17.3"
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/logs
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - /etc/localtime:/etc/localtime
#    restart: always
