version: '2'

services:

  nginx:
    image: "nginx:1.15"
    ports:
      - "80:80"
#    restart: always
    volumes:
      #- /etc/localtime:/etc/localtime
      - ./logs:/var/logs
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
